default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: root
      password: root
      port: 5433
      dbname: polish_flat
      schema: public
      threads: 8
      priority: interactive
