default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 'pgdatabase'
      user: 'root'
      password: 'root'
      port: 5432
      dbname: 'polish_flat'
      schema: 'public'
      threads: 8
      priority: interactive