name: 'polish_flats_dbt'
version: '1.0'
config-version: 2

profile: 'default'  # This tells dbt to use the profile from profiles.yml

# This specifies the directory where DBT will look for models.
model-paths:
  - models
